language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  include:
    - rvm: jruby-9.1.17.0
      jdk: openjdk8
      name: "JRuby 9.1"
    - rvm: jruby-9.2.11.1
      jdk: openjdk11
      name: "JRuby 9.2"

  allow_failures:
    - rvm: ruby-head
    # Revisit when fixing https://github.com/jruby/jruby/issues/4678
    - name: "JRuby 9.2"
  fast_finish: true

env:
  global:
    - JRUBY_OPTS="--debug"

script:
    - rake test
    - rake test_rspec
