language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-9.1.5.0

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

script:
    - rake test
    - rake test_rspec
